### ISSUE TITLE
Very frequently, getting max retries exceeded with URL on AWS S3

### ISSUE THREAD

**Issue by ksingh7** [red-hat-data-services/jumpstart-library#13]
Very frequently, getting max retries exceeded with URL on AWS S3 , in LPR_Service
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='public-license-plate-dataset.s3.ap-south-1.amazonaws.com', port=443): Max retries exceeded with url: /0.png (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1fd4042340>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by guimou** [comment]
Yes, I frequently have name resolution issues on Perf3. This is what you
have at the end of the error message.
Unfortunately I think it comes from the network in the Lab, which is really
bad, lagging and slow...

**Comment by guimou** [comment]
In new version, images are copied locally as part of the installation, they are not pulled from AWS any more. This solves the issue, closing it.
